export const GOOGLE_API_KEY = 'google_api_key'
export const FACEBOOK_API_KEY = 'facebook_api_key'
export const RADIUS_1 = 'radius-1'
export const RADIUS_2 = 'radius-2'
export const RADIUS_3 = 'radius-3'
export const TYPE = 'console_settings'