export const CAMPAIGN_TYPE = 'OFFER';
export const DEFAULT_HYPERX_CAMPAIGN_STATES = [
  'LIVE',
  'UPCOMING',
  'COMPLETE',
  'DRAFT',
  'PAUSE',
  'PRE_LIVE_PROCESSING',
];
export const TEMPLATE_STYLE = 'MUSTACHE';
export const DEFAULT_QUEUE = 'HYPERX_EVENTS_QUEUE';
export const DEFAULT_ACTIVE_STATUS = 'ACTIVE';
export const DEFAULT_INACTIVE_STATUS = 'INACTIVE';
export const DEFAULT_HYPERX_CAMPAIGN = ['OFFER', 'MESSAGING'];
export const SHOULD_EDIT = ['DRAFT', 'PAUSE'];
export const DEFAULT_RULE_TYPE = 'SIMPLE';
