export const data = [
  {
    image: 'https://i.pravatar.cc/50',
    firstName: 'Merilyn',
    lastName: 'Colombo',
    role: 'Admin',
    email: 'kidsenh@outlook.com',
    orgLevel: 'Big Bazar, India',
    status: 'Pending',
    creator: 'Devid Tailor',
    Assign: false,
  },
  {
    image: 'https://i.pravatar.cc/101',
    firstName: 'Laila',
    lastName: 'Zylstra',
    role: 'Campaign Manager',
    email: 'kidsenh@outlook.com',
    orgLevel: 'Big Bazar, India',
    status: 'Active',
    creator: 'Devid Tailor',
    Assign: false,
  },
  ,
  {
    image: '',
    firstName: 'Super',
    lastName: 'Mario',
    role: 'Admin',
    email: 'alkgozx@outlook.com',
    orgLevel: 'Not Assigned',
    status: 'Active',
    creator: 'Devid Tailor',
    Assign: true,
  },
  {
    image: 'https://i.pravatar.cc/53',
    firstName: 'Bus',
    lastName: 'banner',
    role: 'Opearation Manager',
    email: 'hulk@outlook.com',
    orgLevel: 'Big Bazar, South India',
    status: 'Blocked',
    creator: 'Anthony Russo',
    Assign: false,
  },
  {
    image: '',
    firstName: 'John',
    lastName: 'Mario',
    role: 'Store Manager',
    email: 'john@outlook.com',
    orgLevel: 'Not Assigned',
    status: 'Active',
    creator: 'Devid Tailor',
    Assign: true,
  },
  {
    image: 'https://i.pravatar.cc/54',
    firstName: 'Merilyn',
    lastName: 'Colombo',
    role: 'Admin',
    email: 'kidsenh@outlook.com',
    orgLevel: 'Big Bazar, India',
    status: 'Pending',
    creator: 'Devid Tailor',
    Assign: false,
  },
  {
    image: 'https://i.pravatar.cc/55',
    firstName: 'Bus',
    lastName: 'banner',
    role: 'Admin',
    email: 'hulk@outlook.com',
    orgLevel: 'Big Bazar, South India',
    status: 'Active',
    creator: 'Anthony Russo',
    Assign: false,
  },
  {
    image: '',
    firstName: 'Super',
    lastName: 'Mario',
    role: 'Opearation Manager',
    email: 'alkgozx@outlook.com',
    orgLevel: 'Not Assigned',
    status: 'Active',
    creator: 'Devid Tailor',
    Assign: true,
  },
];

export const data1 = [
  {
    image: 'https://i.pravatar.cc/103',
    firstName: 'Bus',
    lastName: 'banner',
    role: 'Admin',
    email: 'hulk@outlook.com',
    orgLevel: 'Big Bazar, South India',
    status: 'Active',
    creator: 'Anthony Russo',
    Assign: false,
  },
  {
    image: '',
    firstName: 'Super',
    lastName: 'Mario',
    role: 'Opearation Manager',
    email: 'alkgozx@outlook.com',
    orgLevel: 'Not Assigned',
    status: 'Blocked',
    creator: 'Devid Tailor',
    Assign: true,
  },
  {
    image: 'https://i.pravatar.cc/60',
    firstName: 'Laila',
    lastName: 'Zylstra',
    role: 'Campaign Manager',
    email: 'kidsenh@outlook.com',
    orgLevel: 'Big Bazar, India',
    status: 'Active',
    creator: 'Devid Tailor',
    Assign: false,
  },
  {
    image: 'https://i.pravatar.cc/50',
    firstName: 'Merilyn',
    lastName: 'Colombo',
    role: 'Admin',
    email: 'kidsenh@outlook.com',
    orgLevel: 'Big Bazar, India',
    status: 'Pending',
    creator: 'Devid Tailor',
    Assign: false,
  },
  {
    image: '',
    firstName: 'John',
    lastName: 'Mario',
    role: 'Store Manager',
    email: 'john@outlook.com',
    orgLevel: 'Not Assigned',
    status: 'Active',
    creator: 'Devid Tailor',
    Assign: true,
  },
  {
    image: 'https://i.pravatar.cc/70',
    firstName: 'Merilyn',
    lastName: 'Colombo',
    role: 'Admin',
    email: 'kidsenh@outlook.com',
    orgLevel: 'Big Bazar, India',
    status: 'Pending',
    creator: 'Devid Tailor',
    Assign: false,
  },
  {
    image: 'https://i.pravatar.cc/57',
    firstName: 'Bus',
    lastName: 'banner',
    role: 'Admin',
    email: 'hulk@outlook.com',
    orgLevel: 'Big Bazar, South India',
    status: 'Active',
    creator: 'Anthony Russo',
    Assign: false,
  },
  {
    image: '',
    firstName: 'Super',
    lastName: 'Mario',
    role: 'Opearation Manager',
    email: 'alkgozx@outlook.com',
    orgLevel: 'Not Assigned',
    status: 'Active',
    creator: 'Devid Tailor',
    Assign: true,
  },
];
